name: 'Build Jar'
description: 'Sets up Java and builds a Jar file'

inputs:
  phase:
    description: 'Which Maven phase (or goal) should be invoked? Multiple phases can be passed as space separated list.'
    required: true
    default: 'verify'
  run-tests:
    description: 'Execute tests?'
    required: true
    default: 'true'
  # Allows to filter tests by tags.
  #
  # Details:
  # - https://docs.junit.org/current/user-guide/#running-tests-tag-expressions
  included-tags:
    description: 'Tag expression that defines, which tests will be included.'
    required: false
    # Include all tests per default (untagged tests as well as tests with any tag).
    default: 'none() | any()'
  additional-arguments:
    description: 'Additional arguments to pass to Maven.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up JDK 25
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: "25"
        distribution: "temurin"
        cache: maven
    - name: Build with Maven
      env:
        # Do not log dependency downloads.
        # These are common as the runner might run on a node with empty local Maven repository.
        # References:
        # - https://blogs.itemis.com/en/in-a-nutshell-removing-artifact-messages-from-maven-log-output
        # - https://maven.apache.org/ref/3.6.1/maven-embedder/cli.html
        MAVEN_ARGUMENTS: "--batch-mode --no-transfer-progress"
        # Derive the "skipTests" parameter from the "run-tests" input.
        SKIP_TESTS: "${{ inputs.run-tests != 'true' && 'true' || 'false' }}"
        TEST_GROUPS: "${{ inputs.included-tags }}"
        PHASE: "${{ inputs.phase }}"
        ADDITIONAL_ARGUMENTS: "${{ inputs.additional-arguments }}"
      run: "./mvnw ${MAVEN_ARGUMENTS} -DskipTests=${SKIP_TESTS} \"-Dgroups=${TEST_GROUPS}\" ${ADDITIONAL_ARGUMENTS} ${PHASE}"
      shell: sh
