name: Has the changelog been updated?

on:
  pull_request:
    branches: ["main"]
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check-changelog:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Check changelog
        uses: ./.github/workflows/actions/check-changelog
